#ifndef BUSMODULECOMMANDS_H_
#define BUSMODULECOMMANDS_H_

// commands (from Master)
#define TWI_CMD_GET_TYPE				0
#define TWI_CMD_GET_SUMMARY				1
#define TWI_CMD_GET_RELAY_STATE			2
#define TWI_CMD_SET_RELAY_STATE			3
#define TWI_CMD_GET_TEMPERATURE			4



#endif /* BUSMODULECOMMANDS_H_ */